"""Realistic seed/mock data for agents that need external data sources.

This provides development-time data for TrafficAgent, HotelAgent, FoodAgent,
and AttractionAgent before real API integrations are wired up.
"""

# ── Hotel mock data ────────────────────────────────────────

HOTEL_SEED = {
    "Beijing": [
        {
            "name": "Beijing International Hotel",
            "location": "Jianguomenwai Street, Chaoyang",
            "star": 5,
            "price_per_night": 680,
            "rating": 4.7,
            "amenities": ["wifi", "pool", "gym", "spa", "restaurant"],
            "distance_to_center_km": 1.5,
            "subway_station": "Jianguomen (Line 1/2)",
            "highlights": "Business district, walk to Forbidden City in 20min",
        },
        {
            "name": "Wangfujing Grand Hotel",
            "location": "Wangfujing Street, Dongcheng",
            "star": 4,
            "price_per_night": 420,
            "rating": 4.5,
            "amenities": ["wifi", "gym", "restaurant", "laundry"],
            "distance_to_center_km": 0.5,
            "subway_station": "Wangfujing (Line 1)",
            "highlights": "Walking distance to Forbidden City and shopping street",
        },
        {
            "name": "Nanluoguxiang Courtyard Hotel",
            "location": "Nanluoguxiang Hutong, Dongcheng",
            "star": 3,
            "price_per_night": 280,
            "rating": 4.3,
            "amenities": ["wifi", "courtyard", "bicycle rental", "tea house"],
            "distance_to_center_km": 2.0,
            "subway_station": "Nanluoguxiang (Line 6/8)",
            "highlights": "Traditional hutong courtyard, authentic Beijing experience",
        },
        {
            "name": "Haolaiwu Hotel Xidan",
            "location": "Xidan, Xicheng",
            "star": 3,
            "price_per_night": 200,
            "rating": 4.0,
            "amenities": ["wifi", "24h front desk"],
            "distance_to_center_km": 3.0,
            "subway_station": "Xidan (Line 1/4)",
            "highlights": "Budget-friendly, near shopping district, clean rooms",
        },
    ],
    "Chengdu": [
        {
            "name": "Jinjiang Hotel Chengdu",
            "location": "Renmin South Road, Jinjiang",
            "star": 5,
            "price_per_night": 550,
            "rating": 4.6,
            "amenities": ["wifi", "pool", "spa", "3 restaurants", "concierge"],
            "distance_to_center_km": 1.0,
            "subway_station": "Jinjiang Hotel (Line 1)",
            "highlights": "Landmark hotel, excellent Sichuan restaurant on-site",
        },
        {
            "name": "Kuanzhai Alley Boutique Inn",
            "location": "Kuanzhai Alley, Qingyang",
            "star": 4,
            "price_per_night": 350,
            "rating": 4.4,
            "amenities": ["wifi", "courtyard", "tea ceremony", "local breakfast"],
            "distance_to_center_km": 0.8,
            "subway_station": "Kuanzhaixiangzi (Line 4)",
            "highlights": "Inside the historic Kuanzhai Alley, cultural atmosphere",
        },
        {
            "name": "Hello Chengdu Youth Hostel",
            "location": "Wuhou District, near Sichuan University",
            "star": 2,
            "price_per_night": 60,
            "rating": 4.2,
            "amenities": ["wifi", "common area", "kitchen", "laundry", "bike rental"],
            "distance_to_center_km": 3.5,
            "subway_station": "Sichuan University (Line 3)",
            "highlights": "Social atmosphere, perfect for backpackers, near food street",
        },
    ],
    "Hangzhou": [
        {
            "name": "Four Seasons Hotel Hangzhou at West Lake",
            "location": "Lingyin Road, Xihu",
            "star": 5,
            "price_per_night": 1200,
            "rating": 4.9,
            "amenities": ["wifi", "pool", "spa", "lake view", "garden", "Michelin restaurant"],
            "distance_to_center_km": 2.0,
            "subway_station": "Longxiangqiao (Line 1) + taxi 10min",
            "highlights": "Private West Lake access, traditional garden architecture",
        },
        {
            "name": "West Lake State Guesthouse",
            "location": "Yangong Causeway, Xihu",
            "star": 4,
            "price_per_night": 480,
            "rating": 4.5,
            "amenities": ["wifi", "lake view", "garden", "bicycle", "restaurant"],
            "distance_to_center_km": 1.5,
            "subway_station": "Ding'an Road (Line 1)",
            "highlights": "On West Lake itself, classical gardens, quiet environment",
        },
        {
            "name": "Mingtown Hangzhou International Youth Hostel",
            "location": "Hefang Street, Shangcheng",
            "star": 2,
            "price_per_night": 55,
            "rating": 4.1,
            "amenities": ["wifi", "bar", "common area", "laundry"],
            "distance_to_center_km": 0.5,
            "subway_station": "Ding'an Road (Line 1)",
            "highlights": "Best value near West Lake, travelers community, walking tours",
        },
    ],
    "Shanghai": [
        {
            "name": "The Bund Hotel Shanghai",
            "location": "East Nanjing Road, Huangpu",
            "star": 5,
            "price_per_night": 850,
            "rating": 4.6,
            "amenities": ["wifi", "pool", "spa", "bund view", "fitness center"],
            "distance_to_center_km": 0.3,
            "subway_station": "Nanjing Road East (Line 2/10)",
            "highlights": "Bund view rooms, walk to the Bund promenade",
        },
        {
            "name": "Jinjiang Inn People's Square",
            "location": "Fuzhou Road, Huangpu",
            "star": 2,
            "price_per_night": 180,
            "rating": 3.8,
            "amenities": ["wifi", "24h front desk"],
            "distance_to_center_km": 0.8,
            "subway_station": "People's Square (Line 1/2/8)",
            "highlights": "Budget central location, no-frills but clean and convenient",
        },
    ],
}


# ── Food mock data ─────────────────────────────────────────

FOOD_SEED = {
    "Beijing": [
        {"name": "Quanjude Roast Duck (Qianmen)", "cuisine": "Beijing", "type": "lunch,dinner",
         "price_per_person": 150, "rating": 4.3, "specialty": "Peking Duck since 1864",
         "location": "Qianmen Street, Dongcheng", "tips": "Reserve in advance, lunch queue starts at 10:30"},
        {"name": "Da Dong Roast Duck (Dongsi Shitiao)", "cuisine": "Beijing", "type": "lunch,dinner",
         "price_per_person": 200, "rating": 4.6, "specialty": "Lean Peking Duck, innovative presentation",
         "location": "Dongsi Shitiao, Dongcheng", "tips": "Higher-end experience, excellent wine list"},
        {"name": "Haidilao Hot Pot (Xidan)", "cuisine": "Sichuan", "type": "dinner",
         "price_per_person": 120, "rating": 4.5, "specialty": "Premium service, free manicure while you wait",
         "location": "Xidan, Xicheng", "tips": "Go before 17:00 or expect 1h+ wait"},
        {"name": "Dadong Old Beijing Noodles (Beixinqiao)", "cuisine": "Beijing", "type": "lunch",
         "price_per_person": 40, "rating": 4.4, "specialty": "Zhajiangmian (soybean paste noodles)",
         "location": "Beixinqiao, Dongcheng", "tips": "Local institution, simple but authentic"},
        {"name": "Ghost Street (Guijie) Crawfish", "cuisine": "Sichuan", "type": "dinner",
         "price_per_person": 100, "rating": 4.2, "specialty": "Spicy crawfish, open until 4am",
         "location": "Guijie, Dongzhimen", "tips": "Best for late-night dining, lively atmosphere"},
        {"name": "Wangfujing Snack Street", "cuisine": "Beijing", "type": "snack",
         "price_per_person": 30, "rating": 3.9, "specialty": "Candied hawthorn, fried dough, scorpion skewers",
         "location": "Wangfujing, Dongcheng", "tips": "Tourist experience, try the tanghulu (candied fruit)"},
    ],
    "Chengdu": [
        {"name": "Chen Mapo Tofu (Huaxing Street)", "cuisine": "Sichuan", "type": "lunch,dinner",
         "price_per_person": 80, "rating": 4.5, "specialty": "Original mapo tofu since 1862",
         "location": "Huaxing Street, Jinjiang", "tips": "The real deal - numbing and spicy, not for beginners"},
        {"name": "Xiaolongkan Hot Pot (Chunxi Road)", "cuisine": "Sichuan", "type": "dinner",
         "price_per_person": 100, "rating": 4.7, "specialty": "Traditional Chengdu hot pot, beef tripe",
         "location": "Chunxi Road, Jinjiang", "tips": "Order yuan yang guo (half spicy/half mild) if unsure"},
        {"name": "Long Chao Shou (General Fu Road)", "cuisine": "Sichuan", "type": "lunch",
         "price_per_person": 30, "rating": 4.3, "specialty": "Chengdu wontons in chili oil",
         "location": "General Fu Road, Qingyang", "tips": "Quick, cheap, and iconic - perfect lunch stop"},
        {"name": "Yu's Grilled Fish (Kuanzhai Alley)", "cuisine": "Sichuan", "type": "dinner",
         "price_per_person": 90, "rating": 4.4, "specialty": "Grilled fish with pickled pepper broth",
         "location": "Kuanzhai Alley, Qingyang", "tips": "Great for groups, choose your fish and toppings"},
        {"name": "Heming Tea House (People's Park)", "cuisine": "Sichuan", "type": "snack",
         "price_per_person": 20, "rating": 4.5, "specialty": "Jasmine tea, ear cleaning, people watching",
         "location": "People's Park, Qingyang", "tips": "Go in the morning, the quintessential Chengdu experience"},
    ],
    "Hangzhou": [
        {"name": "Louwailou (West Lake)", "cuisine": "Zhejiang", "type": "lunch,dinner",
         "price_per_person": 180, "rating": 4.4, "specialty": "West Lake Vinegar Fish, Dongpo Pork",
         "location": "Gushan Road, Xihu", "tips": "Iconic 170-year-old restaurant, seats with lake view"},
        {"name": "Zhiweiguan (Hubin Road)", "cuisine": "Zhejiang", "type": "lunch",
         "price_per_person": 60, "rating": 4.3, "specialty": "Xiaolongbao, wontons, Hangzhou dim sum",
         "location": "Hubin Road, Shangcheng", "tips": "Great dim sum breakfast, try the crab meat xiaolongbao"},
        {"name": "Green Tea Restaurant (Longjing Road)", "cuisine": "Zhejiang", "type": "lunch,dinner",
         "price_per_person": 80, "rating": 4.2, "specialty": "Tea-smoked chicken, farm-to-table",
         "location": "Longjing Road, Xihu", "tips": "Located in tea plantation, beautiful setting"},
    ],
    "Shanghai": [
        {"name": "Nanxiang Steamed Bun (City God Temple)", "cuisine": "Shanghainese", "type": "lunch",
         "price_per_person": 60, "rating": 4.3, "specialty": "Xiaolongbao (soup dumplings)",
         "location": "City God Temple, Huangpu", "tips": "Go to 2F for dine-in, 1F is always packed"},
        {"name": "Jesse Restaurant (Tianping Road)", "cuisine": "Shanghainese", "type": "lunch,dinner",
         "price_per_person": 130, "rating": 4.5, "specialty": "Braised pork belly, drunken chicken",
         "location": "Tianping Road, Xuhui", "tips": "Old-school Shanghainese, reservation recommended"},
        {"name": "Yang's Fried Dumplings (Wujiang Road)", "cuisine": "Shanghainese", "type": "breakfast,snack",
         "price_per_person": 15, "rating": 4.4, "specialty": "Shengjianbao (pan-fried pork buns)",
         "location": "Wujiang Road, Jing'an", "tips": "Eat carefully - hot soup inside! Get 4 for 12 RMB"},
    ],
}


# ── Attraction mock data ───────────────────────────────────

ATTRACTION_SEED = {
    "Beijing": [
        {"name": "Forbidden City", "category": "cultural", "duration": "3-4h", "ticket": 60,
         "open": "8:30-17:00 (closed Mon)", "rating": 4.8, "crowded": "very_high",
         "tips": "Book online 7 days ahead. Enter Meridian Gate. Audio guide highly recommended.",
         "best_time": "8:30-10:00 to avoid crowds"},
        {"name": "Great Wall at Mutianyu", "category": "outdoor", "duration": "5-6h", "ticket": 45,
         "open": "7:30-17:00", "rating": 4.7, "crowded": "high",
         "tips": "Less crowded than Badaling. Take cable car up, toboggan down. Bring water.",
         "best_time": "Arrive by 8:00, morning light is best for photos"},
        {"name": "Temple of Heaven", "category": "cultural", "duration": "2h", "ticket": 15,
         "open": "6:00-21:00", "rating": 4.6, "crowded": "medium",
         "tips": "Morning visit for local tai chi scenes. Echo wall is a must-try.",
         "best_time": "6:00-8:00 for authentic morning atmosphere"},
        {"name": "Summer Palace", "category": "outdoor", "duration": "3-4h", "ticket": 30,
         "open": "7:00-17:00", "rating": 4.6, "crowded": "high",
         "tips": "Take a boat on Kunming Lake. Climb Longevity Hill for panoramic shots.",
         "best_time": "Afternoon for golden hour photos over the lake"},
        {"name": "798 Art District", "category": "entertainment", "duration": "2-3h", "ticket": 0,
         "open": "10:00-18:00 (galleries)", "rating": 4.4, "crowded": "low",
         "tips": "Free entry to most galleries. Great for photos. Cafes everywhere.",
         "best_time": "Weekday afternoons are quietest"},
        {"name": "Nanluoguxiang Hutong", "category": "cultural", "duration": "1-2h", "ticket": 0,
         "open": "all day", "rating": 4.2, "crowded": "high",
         "tips": "Explore the side alleys for quieter spots. Try local snacks along the way.",
         "best_time": "Evening for lantern-lit atmosphere"},
    ],
    "Chengdu": [
        {"name": "Giant Panda Breeding Base", "category": "outdoor", "duration": "3-4h", "ticket": 58,
         "open": "7:30-18:00", "rating": 4.7, "crowded": "high",
         "tips": "Arrive before 8:30 to see pandas at feeding time. Morning is most active.",
         "best_time": "7:30-10:00, pandas sleep after lunch"},
        {"name": "Jinli Ancient Street", "category": "shopping", "duration": "1-2h", "ticket": 0,
         "open": "all day (shops 10:00-22:00)", "rating": 4.3, "crowded": "high",
         "tips": "Evening visit for lanterns. Try the stuffed pancakes and cold noodles.",
         "best_time": "18:00-21:00 for best atmosphere"},
        {"name": "Wuhou Shrine", "category": "cultural", "duration": "2h", "ticket": 60,
         "open": "8:00-18:00", "rating": 4.5, "crowded": "medium",
         "tips": "History of Three Kingdoms. Nice gardens. Combine with Jinli next door.",
         "best_time": "Morning when fewer tour groups"},
        {"name": "Mount Qingcheng", "category": "outdoor", "duration": "full day", "ticket": 90,
         "open": "8:00-17:30", "rating": 4.6, "crowded": "medium",
         "tips": "Taoism birthplace. Front mountain easier, back mountain for real hiking.",
         "best_time": "Spring and autumn, avoid summer rain season"},
    ],
    "Hangzhou": [
        {"name": "West Lake (Xihu)", "category": "outdoor", "duration": "half day", "ticket": 0,
         "open": "all day", "rating": 4.7, "crowded": "high",
         "tips": "Walk or bike around the lake (10km loop). Take a boat to islands.",
         "best_time": "Early morning for mist over lake, or sunset at Leifeng Pagoda"},
        {"name": "Lingyin Temple", "category": "cultural", "duration": "2-3h", "ticket": 75,
         "open": "7:00-17:30", "rating": 4.6, "crowded": "high",
         "tips": "One of China's most important Buddhist temples. Feilai Feng grottoes nearby.",
         "best_time": "Morning for incense ceremonies"},
        {"name": "Longjing Tea Plantation", "category": "outdoor", "duration": "2-3h", "ticket": 0,
         "open": "daytime", "rating": 4.4, "crowded": "low",
         "tips": "Walk through tea terraces. Visit in spring for fresh tea tasting.",
         "best_time": "March-May for tea harvest season"},
    ],
    "Shanghai": [
        {"name": "The Bund", "category": "sightseeing", "duration": "1-2h", "ticket": 0,
         "open": "all day", "rating": 4.7, "crowded": "high",
         "tips": "Best views at night when Pudong skyline lights up. Walk from north to south.",
         "best_time": "Sunset to night for the light show"},
        {"name": "Yu Garden", "category": "cultural", "duration": "1.5h", "ticket": 40,
         "open": "8:30-17:00", "rating": 4.4, "crowded": "high",
         "tips": "Classical Ming dynasty garden. Avoid weekends if possible.",
         "best_time": "Morning right at opening for fewer crowds"},
        {"name": "Shanghai Museum", "category": "cultural", "duration": "2-3h", "ticket": 0,
         "open": "9:00-17:00 (closed Mon)", "rating": 4.6, "crowded": "medium",
         "tips": "Free entry. Ancient bronze and ceramics collections are world-class.",
         "best_time": "Weekday afternoons"},
    ],
}


# ── Traffic mock data ──────────────────────────────────────

TRAFFIC_SEED = {
    "Beijing-Chengdu": [
        {"method": "high_speed_train", "duration": "7h 30min", "price": 780, "frequency": "4/day",
         "departure": "Beijing West → Chengdu East", "best": "G89 06:53-14:23"},
        {"method": "flight", "duration": "3h", "price": 1100, "frequency": "15+/day",
         "departure": "PEK → CTU", "best": "Morning flights have best on-time rate"},
        {"method": "sleeper_train", "duration": "22h", "price": 450, "frequency": "2/day",
         "departure": "Beijing West → Chengdu", "best": "Budget option, save one night of hotel"},
    ],
    "Beijing-Shanghai": [
        {"method": "high_speed_train", "duration": "4h 30min", "price": 553, "frequency": "40+/day",
         "departure": "Beijing South → Shanghai Hongqiao", "best": "G1 09:00-13:28"},
        {"method": "flight", "duration": "2h 15min", "price": 800, "frequency": "50+/day",
         "departure": "PEK → SHA (Hongqiao, closer to city)", "best": "Pick Hongqiao airport, not Pudong"},
    ],
    "Shanghai-Hangzhou": [
        {"method": "high_speed_train", "duration": "45min", "price": 73, "frequency": "100+/day",
         "departure": "Shanghai Hongqiao → Hangzhou East", "best": "Basically a commuter route"},
        {"method": "car", "duration": "2h 30min", "price": 300, "frequency": "anytime",
         "departure": "G60 expressway", "best": "Convenient if traveling with luggage"},
    ],
    "Chengdu-Chongqing": [
        {"method": "high_speed_train", "duration": "1h 30min", "price": 154, "frequency": "50+/day",
         "departure": "Chengdu East → Chongqing West", "best": "Frequent departures, no reservation needed"},
    ],
}

# Default city-center distances for common transit estimates
CITY_DISTANCES: dict[str, dict[str, float]] = {
    "Beijing": {"airport_to_city_km": 28, "train_station_to_center_km": 5},
    "Chengdu": {"airport_to_city_km": 18, "train_station_to_center_km": 7},
    "Shanghai": {"airport_to_city_km": 13, "train_station_to_center_km": 8},
    "Hangzhou": {"airport_to_city_km": 28, "train_station_to_center_km": 5},
}
